name = "TUN Starting Position Markers & BFT";
picture = "Data\afilogo.paa";
actionName = "Community Website";
action = "https://armafinland.fi/";
description = "Create starting position markers for squads, vehicles and other stuff like ammo boxes for specifig side";
logo = "Data\afilogo.paa";
logoOver = "Data\afilogo.paa";
logoSmall = "Data\afilogo.paa";
tooltip = "TUN Start pos markers";
tooltipOwned = "TUN Start pos markers";
overview = "Create starting position markers for squads, vehicles and other stuff like ammo boxes for specifig side";
author = "Tuntematon";
//overviewPicture = "";
overviewText = "TUN Start pos markers";
//overviewFootnote = "<br /><br /><t color='#999999'>Teksti<t />";